apiVersion: v1
kind: Secret
metadata:
  name: project-secret
type: Opaque
data:
  DB: bW9uZ29kYitzcnY6Ly9waG9uZ3RyYW4yNzA5OTc6UGhvbmcxMjM0NUBuaWtpZGFzLmN4d2hqLm1vbmdvZGIubmV0L25pa2lkYXM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  jwtPrivateKey: ZGV2b3BzZ2Vueg==
